name: reddit_clone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  any_link_preview: ^3.0.1
  cloud_firestore: ^4.15.3
  dotted_border: ^2.1.0
  file_picker: ^6.1.1
  firebase_auth: ^4.17.3
  firebase_core: ^2.25.3
  firebase_storage: ^11.6.4
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  fpdart: ^1.1.0
  google_sign_in: ^6.2.1
  routemaster: ^1.0.1
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/google.png
   - assets/images/logo.png
   - assets/images/loginEmote.png
   - assets/images/awards/